<?php

define('VIEWS_NUMBER_FIELD_CALC_FIELD', 'views_number_field_calc');

/**
 * Implements Hook_views_api().
 */
function views_number_field_calc_views_api() {
  return array(
    'api'  => '3.0',
    'path' => drupal_get_path('module', 'views_number_field_calc') . '/views'
  );
}

/**
 * Field detection.
 * 
 * @param String $subject
 * @return Boolean
 */
function views_number_field_detection($subject) {
  return preg_match('~^'.VIEWS_NUMBER_FIELD_CALC_FIELD.'(_[0-9]+)?$~', $subject);
}
