<?php

define('VIEWS_NUMBER_FIELD_TOTAL_FIELD', 'number_field_total_field');

/**
 * Implements Hook_views_api
 */
function views_number_field_total_views_api() {
  return array(
    'api'  => '3.0',
    'path' => drupal_get_path('module', 'views_number_field_total') . '/views'
  );
}

/**
 * Field detection
 * @param String $subject
 * @return Boolean
 */
function views_number_field_detection($subject) {
  return preg_match('~^'.VIEWS_NUMBER_FIELD_TOTAL_FIELD.'(_[0-9]+)?$~', $subject);
}
